[package]
name = "oas2pdf"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
color-eyre = "0.6.3"
indexmap = "2.6.0"
openapiv3-extended = "6.0.0"
serde_json = "1.0.128"
serde_yaml = "0.9.34"
