openapi: 3.0.0
info:
  title: Several Methods API
  description: A simple API with a request body
  version: v1.21
paths:
  /post:
    post:
      summary: Post things
      description: Post things
      operationId: PostThings
      parameters:
        - name: thing
          in: path
          description: ID of thing to post
          schema:
            type: number
      requestBody:
        content:
          application/json:
            schema:
              type: string
          text/plain:
            schema:
              type: string
        description: >-
          The input stream must be a tar archive compressed with one of the
          following algorithms: identity (no compression), gzip, bzip2, xz.
      responses:
        '200':
          description: no error
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
            text/plain:
              schema:
                type: array
                items:
                  type: integer
        '400':
          description: bad parameter
        '500':
          description: server error
      tags:
        - Container
